apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: 127.0.0.1.nip.io   # Valid DNS hostname (nip.io will resolve to 127.0.0.1)
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: react-app-service
                port:
                  number: 3000   # Use your exposed service port (not 55834)
