apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 3000         # Changed the exposed port to 3000
      targetPort: 3000   # Changed the target port to 3000
  type: LoadBalancer
